### PR TITLE
Create about.html

### PR DESCRIPTION
**Pull request by sunnyflight**

### CODE REVIEW

**Comment by kmss21** [comment]
Hi SJ

**Comment by sunnyflight** [comment]
Hi Issac

**Comment by kmss21** [comment]
Hi @sunnyflight Hi

**Comment by kmss21** [comment]
Let me introduce @chilicrab hahaha

**Comment by chilicrab** [comment]
hello

**Comment by kmss21** [comment]
Show me the money!!!!!

**Comment by kmss21** [comment]
please call 911

**Comment by kmss21** [comment]
Samsung is three star

**Comment by kmss21** [comment]
Please add on your 'about' page that you've worked in Samsung

**Pull request merged**
